

const main = async (req, res, next) => {
    try {
        //Validar esquema

        //Enviar al servicio los datos

        //Responder
    } catch (error) {
        next(error);
    }
}